INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AFG',004,'Afghanistan','Afghanistan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ALA',248,'Aland Islands','Aland Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ALB',008,'Albania','Albania');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('DZA',012,'Algeria','Algeria');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ASM',016,'American Samoa','American Samoa');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AND',020,'Andorra','Andorra');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AGO',024,'Angola','Angola');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AIA',660,'Anguilla','Anguilla');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ATA',010,'Antarctica','Antarctica');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ATG',028,'Antigua and Barbuda','Antigua and Barbuda');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ARG',032,'Argentina','Argentina');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ARM',051,'Armenia','Armenia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ABW',533,'Aruba','Aruba');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AUS',036,'Australia','Australia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AUT',040,'Austria','Austria');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('AZE',031,'Azerbaijan','Azerbaijan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BHS',044,'Bahamas (the)','Bahamas');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BHR',048,'Bahrain','Bahrain');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BGD',050,'Bangladesh','Bangladesh');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BRB',052,'Barbados','Barbados');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BLR',112,'Belarus','Belarus');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BEL',056,'Belgium','Belgium');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BLZ',084,'Belize','Belize');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BEN',204,'Benin','Benin');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BMU',060,'Bermuda','Bermuda');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BTN',064,'Bhutan','Bhutan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BOL',068,'Bolivia (Plurinational State of)','Bolivia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BES',535,'Bonaire, Sint Eustatius and Saba','Bonaire');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BIH',070,'Bosnia and Herzegovina','Bosnia and Herzegovina');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BWA',072,'Botswana','Botswana');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BVT',074,'Bouvet Island','Bouvet Island');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BRA',076,'Brazil','Brazil');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IOT',086,'British Indian Ocean Territory (the)','British Indian Ocean Territory');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BRN',096,'Brunei Darussalam','Brunei Darussalam');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BGR',100,'Bulgaria','Bulgaria');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BFA',854,'Burkina Faso','Burkina Faso');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BDI',108,'Burundi','Burundi');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CPV',132,'Cabo Verde','Cabo Verde');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KHM',116,'Cambodia','Cambodia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CMR',120,'Cameroon','Cameroon');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CAN',124,'Canada','Canada');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CYM',136,'Cayman Islands (the)','Cayman Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CAF',140,'Central African Republic (the)','Central African Republic');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TCD',148,'Chad','Chad');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CHL',152,'Chile','Chile');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CHN',156,'China','China');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CXR',162,'Christmas Island','Christmas Island');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CCK',166,'Cocos (Keeling) Islands (the)','Cocos Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('COL',170,'Colombia','Colombia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('COM',174,'Comoros (the)','Comoros');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('COD',180,'Congo (the Democratic Republic of the)','Democratic Republic of the Congo');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('COG',178,'Congo (the)','Congo');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('COK',184,'Cook Islands (the)','Cook Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CRI',188,'Costa Rica','Costa Rica');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('HRV',191,'Croatia','Croatia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CUB',192,'Cuba','Cuba');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CUW',531,'Cura�ao','Cura�ao');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CYP',196,'Cyprus','Cyprus');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CZE',203,'Czechia','Czechia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CIV',384,'C�te d''Ivoire','C�te d''Ivoire');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('DNK',208,'Denmark','Denmark');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('DJI',262,'Djibouti','Djibouti');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('DMA',212,'Dominica','Dominica');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('DOM',214,'Dominican Republic (the)','Dominican Republic');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ECU',218,'Ecuador','Ecuador');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('EGY',818,'Egypt','Egypt');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SLV',222,'El Salvador','El Salvador');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GNQ',226,'Equatorial Guinea','Equatorial Guinea');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ERI',232,'Eritrea','Eritrea');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('EST',233,'Estonia','Estonia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SWZ',748,'Eswatini','Eswatini');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ETH',231,'Ethiopia','Ethiopia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('FLK',238,'Falkland Islands (the) [Malvinas]','Falkland Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('FRO',234,'Faroe Islands (the)','Faroe Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('FJI',242,'Fiji','Fiji');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('FIN',246,'Finland','Finland');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('FRA',250,'France','France');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GUF',254,'French Guiana','French Guiana');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PYF',258,'French Polynesia','French Polynesia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ATF',260,'French Southern Territories (the)','French Southern Territories');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GAB',266,'Gabon','Gabon');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GMB',270,'Gambia (the)','Gambia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GEO',268,'Georgia','Georgia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('DEU',276,'Germany','Germany');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GHA',288,'Ghana','Ghana');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GIB',292,'Gibraltar','Gibraltar');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GRC',300,'Greece','Greece');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GRL',304,'Greenland','Greenland');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GRD',308,'Grenada','Grenada');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GLP',312,'Guadeloupe','Guadeloupe');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GUM',316,'Guam','Guam');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GTM',320,'Guatemala','Guatemala');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GGY',831,'Guernsey','Guernsey');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GIN',324,'Guinea','Guinea');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GNB',624,'Guinea-Bissau','Guinea-Bissau');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GUY',328,'Guyana','Guyana');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('HTI',332,'Haiti','Haiti');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('HMD',334,'Heard Island and McDonald Islands','Heard Island and McDonald Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VAT',336,'Holy See (the)','Vatican');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('HND',340,'Honduras','Honduras');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('HKG',344,'Hong Kong','Hong Kong');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('HUN',348,'Hungary','Hungary');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ISL',352,'Iceland','Iceland');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IND',356,'India','India');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IDN',360,'Indonesia','Indonesia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IRN',364,'Iran (Islamic Republic of)','Iran');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IRQ',368,'Iraq','Iraq');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IRL',372,'Ireland','Ireland');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('IMN',833,'Isle of Man','Isle of Man');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ISR',376,'Israel','Israel');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ITA',380,'Italy','Italy');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('JAM',388,'Jamaica','Jamaica');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('JPN',392,'Japan','Japan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('JEY',832,'Jersey','Jersey');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('JOR',400,'Jordan','Jordan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KAZ',398,'Kazakhstan','Kazakhstan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KEN',404,'Kenya','Kenya');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KIR',296,'Kiribati','Kiribati');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PRK',408,'Korea (the Democratic People''s Republic of)','North Korea');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KOR',410,'Korea (the Republic of)','South Korea');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KWT',414,'Kuwait','Kuwait');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KGZ',417,'Kyrgyzstan','Kyrgyzstan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LAO',418,'Lao People''s Democratic Republic (the)','Laos');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LVA',428,'Latvia','Latvia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LBN',422,'Lebanon','Lebanon');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LSO',426,'Lesotho','Lesotho');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LBR',430,'Liberia','Liberia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LBY',434,'Libya','Libya');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LIE',438,'Liechtenstein','Liechtenstein');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LTU',440,'Lithuania','Lithuania');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LUX',442,'Luxembourg','Luxembourg');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MAC',446,'Macao','Macao');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MDG',450,'Madagascar','Madagascar');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MWI',454,'Malawi','Malawi');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MYS',458,'Malaysia','Malaysia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MDV',462,'Maldives','Maldives');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MLI',466,'Mali','Mali');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MLT',470,'Malta','Malta');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MHL',584,'Marshall Islands (the)','Marshall Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MTQ',474,'Martinique','Martinique');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MRT',478,'Mauritania','Mauritania');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MUS',480,'Mauritius','Mauritius');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MYT',175,'Mayotte','Mayotte');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MEX',484,'Mexico','Mexico');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('FSM',583,'Micronesia (Federated States of)','Micronesia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MDA',498,'Moldova (the Republic of)','Moldova');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MCO',492,'Monaco','Monaco');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MNG',496,'Mongolia','Mongolia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MNE',499,'Montenegro','Montenegro');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MSR',500,'Montserrat','Montserrat');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MAR',504,'Morocco','Morocco');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MOZ',508,'Mozambique','Mozambique');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MMR',104,'Myanmar','Myanmar');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NAM',516,'Namibia','Namibia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NRU',520,'Nauru','Nauru');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NPL',524,'Nepal','Nepal');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NLD',528,'Netherlands (the)','Netherlands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NCL',540,'New Caledonia','New Caledonia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NZL',554,'New Zealand','New Zealand');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NIC',558,'Nicaragua','Nicaragua');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NER',562,'Niger (the)','Niger');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NGA',566,'Nigeria','Nigeria');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NIU',570,'Niue','Niue');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NFK',574,'Norfolk Island','Norfolk Island');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MNP',580,'Northern Mariana Islands (the)','Northern Mariana Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('NOR',578,'Norway','Norway');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('OMN',512,'Oman','Oman');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PAK',586,'Pakistan','Pakistan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PLW',585,'Palau','Palau');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PSE',275,'Palestine, State of','Palestine');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PAN',591,'Panama','Panama');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PNG',598,'Papua New Guinea','Papua New Guinea');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PRY',600,'Paraguay','Paraguay');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PER',604,'Peru','Peru');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PHL',608,'Philippines (the)','Philippines');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PCN',612,'Pitcairn','Pitcairn');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('POL',616,'Poland','Poland');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PRT',620,'Portugal','Portugal');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('PRI',630,'Puerto Rico','Puerto Rico');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('QAT',634,'Qatar','Qatar');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MKD',807,'Republic of North Macedonia','Republic of North Macedonia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ROU',642,'Romania','Romania');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('RUS',643,'Russian Federation (the)','Russian Federation');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('RWA',646,'Rwanda','Rwanda');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('REU',638,'Reunion','Reunion');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('BLM',652,'Saint Barthelemy','Saint Barthelemy');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SHN',654,'Saint Helena, Ascension and Tristan da Cunha','Saint Helena');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('KNA',659,'Saint Kitts and Nevis','Saint Kitts and Nevis');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LCA',662,'Saint Lucia','Saint Lucia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('MAF',663,'Saint Martin (French part)','Saint Martin');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SPM',666,'Saint Pierre and Miquelon','Saint Pierre and Miquelon');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VCT',670,'Saint Vincent and the Grenadines','Saint Vincent and the Grenadines');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('WSM',882,'Samoa','Samoa');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SMR',674,'San Marino','San Marino');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('STP',678,'Sao Tome and Principe','Sao Tome and Principe');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SAU',682,'Saudi Arabia','Saudi Arabia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SEN',686,'Senegal','Senegal');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SRB',688,'Serbia','Serbia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SYC',690,'Seychelles','Seychelles');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SLE',694,'Sierra Leone','Sierra Leone');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SGP',702,'Singapore','Singapore');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SXM',534,'Sint Maarten (Dutch part)','Sint Maarten');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SVK',703,'Slovakia','Slovakia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SVN',705,'Slovenia','Slovenia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SLB',90,'Solomon Islands','Solomon Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SOM',706,'Somalia','Somalia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ZAF',710,'South Africa','South Africa');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SGS',239,'South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SSD',728,'South Sudan','South Sudan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ESP',724,'Spain','Spain');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('LKA',144,'Sri Lanka','Sri Lanka');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SDN',729,'Sudan (the)','Sudan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SUR',740,'Suriname','Suriname');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SJM',744,'Svalbard and Jan Mayen','Svalbard and Jan Mayen');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SWE',752,'Sweden','Sweden');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('CHE',756,'Switzerland','Switzerland');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('SYR',760,'Syrian Arab Republic','Syrian Arab Republic');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TWN',158,'Taiwan (Province of China)','Taiwan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TJK',762,'Tajikistan','Tajikistan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TZA',834,'Tanzania, United Republic of','Tanzania');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('THA',764,'Thailand','Thailand');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TLS',626,'Timor-Leste','Timor-Leste');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TGO',768,'Togo','Togo');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TKL',772,'Tokelau','Tokelau');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TON',776,'Tonga','Tonga');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TTO',780,'Trinidad and Tobago','Trinidad and Tobago');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TUN',788,'Tunisia','Tunisia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TUR',792,'Turkey','Turkey');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TKM',795,'Turkmenistan','Turkmenistan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TCA',796,'Turks and Caicos Islands (the)','Turks and Caicos Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('TUV',798,'Tuvalu','Tuvalu');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('UGA',800,'Uganda','Uganda');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('UKR',804,'Ukraine','Ukraine');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ARE',784,'United Arab Emirates (the)','United Arab Emirates');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('GBR',826,'United Kingdom of Great Britain and Northern Ireland (the)','United Kingdom');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('UMI',581,'United States Minor Outlying Islands (the)','United States Minor Outlying Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('USA',840,'United States of America (the)','United States of America');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('URY',858,'Uruguay','Uruguay');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('UZB',860,'Uzbekistan','Uzbekistan');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VUT',548,'Vanuatu','Vanuatu');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VEN',862,'Venezuela (Bolivarian Republic of)','Venezuela');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VNM',704,'Viet Nam','Viet Nam');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VGB',92,'Virgin Islands (British)','British Virgin Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('VIR',850,'Virgin Islands (U.S.)','U.S. Virgin Islands');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('WLF',876,'Wallis and Futuna','Wallis and Futuna');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ESH',732,'Western Sahara','Western Sahara');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('YEM',887,'Yemen','Yemen');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ZMB',894,'Zambia','Zambia');
INSERT INTO staging.iso_countries(iso3,iso_num,country,country_common) VALUES ('ZWE',716,'Zimbabwe','Zimbabwe');