INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AF','AFG','004','Afghanistan','Afghanistan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AX','ALA','248','Aland Islands','Aland Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AL','ALB','008','Albania','Albania');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('DZ','DZA','012','Algeria','Algeria');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AS','ASM','016','American Samoa','American Samoa');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AD','AND','020','Andorra','Andorra');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AO','AGO','024','Angola','Angola');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AI','AIA','660','Anguilla','Anguilla');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AQ','ATA','010','Antarctica','Antarctica');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AG','ATG','028','Antigua and Barbuda','Antigua and Barbuda');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AR','ARG','032','Argentina','Argentina');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AM','ARM','051','Armenia','Armenia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AW','ABW','533','Aruba','Aruba');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AU','AUS','036','Australia','Australia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AT','AUT','040','Austria','Austria');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AZ','AZE','031','Azerbaijan','Azerbaijan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BS','BHS','044','Bahamas (the)','Bahamas');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BH','BHR','048','Bahrain','Bahrain');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BD','BGD','050','Bangladesh','Bangladesh');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BB','BRB','052','Barbados','Barbados');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BY','BLR','112','Belarus','Belarus');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BE','BEL','056','Belgium','Belgium');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BZ','BLZ','084','Belize','Belize');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BJ','BEN','204','Benin','Benin');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BM','BMU','060','Bermuda','Bermuda');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BT','BTN','064','Bhutan','Bhutan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BO','BOL','068','Bolivia (Plurinational State of)','Bolivia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BQ','BES','535','Bonaire, Sint Eustatius and Saba','Bonaire');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BA','BIH','070','Bosnia and Herzegovina','Bosnia and Herzegovina');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BW','BWA','072','Botswana','Botswana');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BV','BVT','074','Bouvet Island','Bouvet Island');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BR','BRA','076','Brazil','Brazil');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IO','IOT','086','British Indian Ocean Territory (the)','British Indian Ocean Territory');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BN','BRN','096','Brunei Darussalam','Brunei Darussalam');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BG','BGR','100','Bulgaria','Bulgaria');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BF','BFA','854','Burkina Faso','Burkina Faso');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BI','BDI','108','Burundi','Burundi');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CV','CPV','132','Cabo Verde','Cabo Verde');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KH','KHM','116','Cambodia','Cambodia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CM','CMR','120','Cameroon','Cameroon');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CA','CAN','124','Canada','Canada');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KY','CYM','136','Cayman Islands (the)','Cayman Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CF','CAF','140','Central African Republic (the)','Central African Republic');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TD','TCD','148','Chad','Chad');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CL','CHL','152','Chile','Chile');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CN','CHN','156','China','China');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CX','CXR','162','Christmas Island','Christmas Island');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CC','CCK','166','Cocos (Keeling) Islands (the)','Cocos Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CO','COL','170','Colombia','Colombia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KM','COM','174','Comoros (the)','Comoros');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CD','COD','180','Congo (the Democratic Republic of the)','Democratic Republic of the Congo');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CG','COG','178','Congo (the)','Congo');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CK','COK','184','Cook Islands (the)','Cook Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CR','CRI','188','Costa Rica','Costa Rica');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('HR','HRV','191','Croatia','Croatia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CU','CUB','192','Cuba','Cuba');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CW','CUW','531','Cura�ao','Cura�ao');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CY','CYP','196','Cyprus','Cyprus');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CZ','CZE','203','Czechia','Czechia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CI','CIV','384','C�te d''Ivoire','C�te d''Ivoire');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('DK','DNK','208','Denmark','Denmark');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('DJ','DJI','262','Djibouti','Djibouti');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('DM','DMA','212','Dominica','Dominica');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('DO','DOM','214','Dominican Republic (the)','Dominican Republic');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('EC','ECU','218','Ecuador','Ecuador');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('EG','EGY','818','Egypt','Egypt');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SV','SLV','222','El Salvador','El Salvador');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GQ','GNQ','226','Equatorial Guinea','Equatorial Guinea');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ER','ERI','232','Eritrea','Eritrea');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('EE','EST','233','Estonia','Estonia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SZ','SWZ','748','Eswatini','Eswatini');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ET','ETH','231','Ethiopia','Ethiopia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('FK','FLK','238','Falkland Islands (the) [Malvinas]','Falkland Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('FO','FRO','234','Faroe Islands (the)','Faroe Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('FJ','FJI','242','Fiji','Fiji');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('FI','FIN','246','Finland','Finland');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('FR','FRA','250','France','France');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GF','GUF','254','French Guiana','French Guiana');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PF','PYF','258','French Polynesia','French Polynesia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TF','ATF','260','French Southern Territories (the)','French Southern Territories');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GA','GAB','266','Gabon','Gabon');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GM','GMB','270','Gambia (the)','Gambia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GE','GEO','268','Georgia','Georgia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('DE','DEU','276','Germany','Germany');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GH','GHA','288','Ghana','Ghana');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GI','GIB','292','Gibraltar','Gibraltar');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GR','GRC','300','Greece','Greece');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GL','GRL','304','Greenland','Greenland');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GD','GRD','308','Grenada','Grenada');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GP','GLP','312','Guadeloupe','Guadeloupe');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GU','GUM','316','Guam','Guam');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GT','GTM','320','Guatemala','Guatemala');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GG','GGY','831','Guernsey','Guernsey');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GN','GIN','324','Guinea','Guinea');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GW','GNB','624','Guinea-Bissau','Guinea-Bissau');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GY','GUY','328','Guyana','Guyana');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('HT','HTI','332','Haiti','Haiti');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('HM','HMD','334','Heard Island and McDonald Islands','Heard Island and McDonald Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VA','VAT','336','Holy See (the)','Vatican');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('HN','HND','340','Honduras','Honduras');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('HK','HKG','344','Hong Kong','Hong Kong');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('HU','HUN','348','Hungary','Hungary');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IS','ISL','352','Iceland','Iceland');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IN','IND','356','India','India');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ID','IDN','360','Indonesia','Indonesia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IR','IRN','364','Iran (Islamic Republic of)','Iran');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IQ','IRQ','368','Iraq','Iraq');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IE','IRL','372','Ireland','Ireland');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IM','IMN','833','Isle of Man','Isle of Man');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IL','ISR','376','Israel','Israel');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('IT','ITA','380','Italy','Italy');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('JM','JAM','388','Jamaica','Jamaica');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('JP','JPN','392','Japan','Japan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('JE','JEY','832','Jersey','Jersey');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('JO','JOR','400','Jordan','Jordan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KZ','KAZ','398','Kazakhstan','Kazakhstan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KE','KEN','404','Kenya','Kenya');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KI','KIR','296','Kiribati','Kiribati');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KP','PRK','408','Korea (the Democratic People''s Republic of)','North Korea');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KR','KOR','410','Korea (the Republic of)','South Korea');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KW','KWT','414','Kuwait','Kuwait');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KG','KGZ','417','Kyrgyzstan','Kyrgyzstan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LA','LAO','418','Lao People''s Democratic Republic (the)','Laos');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LV','LVA','428','Latvia','Latvia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LB','LBN','422','Lebanon','Lebanon');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LS','LSO','426','Lesotho','Lesotho');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LR','LBR','430','Liberia','Liberia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LY','LBY','434','Libya','Libya');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LI','LIE','438','Liechtenstein','Liechtenstein');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LT','LTU','440','Lithuania','Lithuania');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LU','LUX','442','Luxembourg','Luxembourg');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MO','MAC','446','Macao','Macao');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MG','MDG','450','Madagascar','Madagascar');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MW','MWI','454','Malawi','Malawi');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MY','MYS','458','Malaysia','Malaysia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MV','MDV','462','Maldives','Maldives');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ML','MLI','466','Mali','Mali');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MT','MLT','470','Malta','Malta');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MH','MHL','584','Marshall Islands (the)','Marshall Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MQ','MTQ','474','Martinique','Martinique');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MR','MRT','478','Mauritania','Mauritania');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MU','MUS','480','Mauritius','Mauritius');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('YT','MYT','175','Mayotte','Mayotte');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MX','MEX','484','Mexico','Mexico');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('FM','FSM','583','Micronesia (Federated States of)','Micronesia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MD','MDA','498','Moldova (the Republic of)','Moldova');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MC','MCO','492','Monaco','Monaco');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MN','MNG','496','Mongolia','Mongolia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ME','MNE','499','Montenegro','Montenegro');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MS','MSR','500','Montserrat','Montserrat');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MA','MAR','504','Morocco','Morocco');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MZ','MOZ','508','Mozambique','Mozambique');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MM','MMR','104','Myanmar','Myanmar');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NA','NAM','516','Namibia','Namibia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NR','NRU','520','Nauru','Nauru');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NP','NPL','524','Nepal','Nepal');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NL','NLD','528','Netherlands (the)','Netherlands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NC','NCL','540','New Caledonia','New Caledonia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NZ','NZL','554','New Zealand','New Zealand');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NI','NIC','558','Nicaragua','Nicaragua');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NE','NER','562','Niger (the)','Niger');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NG','NGA','566','Nigeria','Nigeria');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NU','NIU','570','Niue','Niue');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NF','NFK','574','Norfolk Island','Norfolk Island');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MP','MNP','580','Northern Mariana Islands (the)','Northern Mariana Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('NO','NOR','578','Norway','Norway');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('OM','OMN','512','Oman','Oman');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PK','PAK','586','Pakistan','Pakistan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PW','PLW','585','Palau','Palau');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PS','PSE','275','Palestine, State of','Palestine');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PA','PAN','591','Panama','Panama');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PG','PNG','598','Papua New Guinea','Papua New Guinea');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PY','PRY','600','Paraguay','Paraguay');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PE','PER','604','Peru','Peru');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PH','PHL','608','Philippines (the)','Philippines');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PN','PCN','612','Pitcairn','Pitcairn');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PL','POL','616','Poland','Poland');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PT','PRT','620','Portugal','Portugal');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PR','PRI','630','Puerto Rico','Puerto Rico');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('QA','QAT','634','Qatar','Qatar');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MK','MKD','807','Republic of North Macedonia','Republic of North Macedonia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('RO','ROU','642','Romania','Romania');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('RU','RUS','643','Russian Federation (the)','Russian Federation');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('RW','RWA','646','Rwanda','Rwanda');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('RE','REU','638','Reunion','Reunion');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('BL','BLM','652','Saint Barthelemy','Saint Barthelemy');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SH','SHN','654','Saint Helena, Ascension and Tristan da Cunha','Saint Helena');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('KN','KNA','659','Saint Kitts and Nevis','Saint Kitts and Nevis');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LC','LCA','662','Saint Lucia','Saint Lucia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('MF','MAF','663','Saint Martin (French part)','Saint Martin');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('PM','SPM','666','Saint Pierre and Miquelon','Saint Pierre and Miquelon');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VC','VCT','670','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('WS','WSM','882','Samoa','Samoa');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SM','SMR','674','San Marino','San Marino');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ST','STP','678','Sao Tome and Principe','Sao Tome and Principe');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SA','SAU','682','Saudi Arabia','Saudi Arabia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SN','SEN','686','Senegal','Senegal');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('RS','SRB','688','Serbia','Serbia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SC','SYC','690','Seychelles','Seychelles');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SL','SLE','694','Sierra Leone','Sierra Leone');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SG','SGP','702','Singapore','Singapore');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SX','SXM','534','Sint Maarten (Dutch part)','Sint Maarten');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SK','SVK','703','Slovakia','Slovakia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SI','SVN','705','Slovenia','Slovenia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SB','SLB','90','Solomon Islands','Solomon Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SO','SOM','706','Somalia','Somalia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ZA','ZAF','710','South Africa','South Africa');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GS','SGS','239','South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SS','SSD','728','South Sudan','South Sudan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ES','ESP','724','Spain','Spain');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('LK','LKA','144','Sri Lanka','Sri Lanka');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SD','SDN','729','Sudan (the)','Sudan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SR','SUR','740','Suriname','Suriname');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SJ','SJM','744','Svalbard and Jan Mayen','Svalbard and Jan Mayen');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SE','SWE','752','Sweden','Sweden');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('CH','CHE','756','Switzerland','Switzerland');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('SY','SYR','760','Syrian Arab Republic','Syrian Arab Republic');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TW','TWN','158','Taiwan (Province of China)','Taiwan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TJ','TJK','762','Tajikistan','Tajikistan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TZ','TZA','834','Tanzania, United Republic of','Tanzania');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TH','THA','764','Thailand','Thailand');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TL','TLS','626','Timor-Leste','Timor-Leste');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TG','TGO','768','Togo','Togo');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TK','TKL','772','Tokelau','Tokelau');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TO','TON','776','Tonga','Tonga');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TT','TTO','780','Trinidad and Tobago','Trinidad and Tobago');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TN','TUN','788','Tunisia','Tunisia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TR','TUR','792','Turkey','Turkey');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TM','TKM','795','Turkmenistan','Turkmenistan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TC','TCA','796','Turks and Caicos Islands (the)','Turks and Caicos Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('TV','TUV','798','Tuvalu','Tuvalu');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('UG','UGA','800','Uganda','Uganda');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('UA','UKR','804','Ukraine','Ukraine');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('AE','ARE','784','United Arab Emirates (the)','United Arab Emirates');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('GB','GBR','826','United Kingdom of Great Britain and Northern Ireland (the)','United Kingdom');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('UM','UMI','581','United States Minor Outlying Islands (the)','United States Minor Outlying Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('US','USA','840','United States of America (the)','United States of America');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('UY','URY','858','Uruguay','Uruguay');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('UZ','UZB','860','Uzbekistan','Uzbekistan');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VU','VUT','548','Vanuatu','Vanuatu');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VE','VEN','862','Venezuela (Bolivarian Republic of)','Venezuela');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VN','VNM','704','Viet Nam','Viet Nam');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VG','VGB','92','Virgin Islands (British)','British Virgin Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('VI','VIR','850','Virgin Islands (U.S.)','U.S. Virgin Islands');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('WF','WLF','876','Wallis and Futuna','Wallis and Futuna');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('EH','ESH','732','Western Sahara','Western Sahara');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('YE','YEM','887','Yemen','Yemen');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ZM','ZMB','894','Zambia','Zambia');
INSERT INTO staging.iso_countries(iso2,iso3,iso_num,country,country_common) VALUES ('ZW','ZWE','716','Zimbabwe','Zimbabwe');
