DROP TABLE IF EXISTS staging.song CASCADE;
DROP TABLE IF EXISTS staging.album CASCADE;
DROP TABLE IF EXISTS staging.artist CASCADE;
DROP TABLE IF EXISTS staging.genre CASCADE;
DROP TABLE IF EXISTS staging.country CASCADE;

DROP SCHEMA IF EXISTS staging CASCADE;
